# Orchestrates a ROS 2 container (Robot2Nerf) and your Nerfstudio container.
# They share host directories for bags and nerf datasets.

services:
  ros2_collector:
    build:
      context: ..
      dockerfile: docker/ros2_robot2nerf.Dockerfile
      args:
        ROS_DISTRO: "humble"  
    image: ros2_robot2nerf:latest
    container_name: ros2_collector
    volumes:
      - ..:/workspace
    working_dir: /workspace
    tty: true
    stdin_open: true

  nerfstudio_lrm:
    build:
      context: ..
      dockerfile: docker/nerfstudio_lrm.Dockerfile
      args:
        CUDA_ARCHITECTURES: "86"
        NERFSTUDIO_VERSION: "main"
    image: nerf_colmap311:latest
    container_name: nerfstudio_lrm
    # GPUs for training (requires NVIDIA Container Toolkit)
    gpus: all
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ..:/workspace
      - ${HOME}/.cache:/root/.cache
    working_dir: /workspace
    tty: true
    stdin_open: true
    ports:
      - "7007:7007"
